services:

  v_et_g_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: vite_et_gourmand
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  v_et_g_web:
    image: php:8.2-apache
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend:/var/www/html
      - ./backend:/var/www/html/backend
    depends_on:
      - v_et_g_db
    command: >
      sh -c "docker-php-ext-install pdo pdo_mysql && apache2-foreground"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: v_et_g_db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - v_et_g_db

